# Main colors
background           #0c0c16
foreground           #d8dee9
selection_background #414166
selection_foreground #ffffff
url_color            #70a7d4
cursor               #d8dee9

# Tabs
active_tab_background   #0c0c16
active_tab_foreground   #d8dee9
inactive_tab_background #2c2c3d
inactive_tab_foreground #414166

# Normal colors
color0 #2c2c3d
color1 #ff6e6e
color2 #9ec875
color3 #ffa759
color4 #70a7d4
color5 #d291e0
color6 #96e0e0
color7 #d8dee9

# Bright colors
color8  #414166
color9  #ff8d8d
color10 #b3d987
color11 #ffc57f
color12 #9bb3d3
color13 #ffa1ff
color14 #9cd8d8
color15 #ffffff
