" WARN: Vimscript function needs to start with a capital letter
" Function to source file if it exists
function! Require(file)
    " Prefix arguments with a vimscript function with `a:` to indicate argument scope
    if filereadable(expand(a:file))
        exe 'source' a:file
    endif
endfunction

call Require("$HOME/.vim/vim-plug.vim")

call Require("$HOME/.vim/config/options.vim")
call Require("$HOME/.vim/config/keymaps.vim")
call Require("$HOME/.vim/config/autocmds.vim")
call Require("$HOME/.vim/config/functions.vim")

call Require("$HOME/.vim/config/plugins.vim")
