# General
#include ~/.config/kitty/themes/tokyo-night.conf
include ~/.config/kitty/themes/midnight-haze.conf
#include ~/.config/omarchy/current/theme/kitty.conf

auto_reload_config 0.1

# Remote
allow_remote_control yes
listen_on unix:@mykitty

# Window
window_padding_width 5
hide_window_decorations yes
confirm_os_window_close 0

# Scrolling
scrollback_lines 10000
wheel_scroll_multiplier 5.0

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 15.0
disable_ligatures always
# Font offset
modify_font underline_position 0
modify_font underline_thickness 100%
modify_font strikethrough_position 0

# Cursor
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Mouse
copy_on_select yes
mouse_map left click ungrabbed no_op

# Bindings
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+shift+n new_os_window
map ctrl+v paste_from_clipboard
mouse_map right press ungrabbed paste_from_clipboard
map ctrl+space>y kitten hints --type word --program -

# Window
enabled_layouts splits
map ctrl+space>bar launch --location=vsplit --cwd=current
map ctrl+space>minus launch --location=hsplit --cwd=current
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l

# Tab
map ctrl+shift+h prev_tab
map ctrl+shift+l next_tab
map ctrl+space>c new_tab
map ctrl+space>ctrl+space goto_tab -1
map ctrl+space>1 goto_tab 1
map ctrl+space>2 goto_tab 2
map ctrl+space>3 goto_tab 3
map ctrl+space>4 goto_tab 4
map ctrl+space>5 goto_tab 5
map ctrl+space>6 goto_tab 6
map ctrl+space>7 goto_tab 7
map ctrl+space>8 goto_tab 8
map ctrl+space>9 goto_tab 9

# Tab style
tab_bar_min_tabs 1
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style round
tab_title_template "({index}){title.split('/')[-1]}"

# INFO: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #cba6f7
inactive_tab_foreground #11111b
inactive_tab_background #7f849c
tab_bar_background      #11111b

# Copy mode - open the scrollback buffer inside nvim with system clipboard enabled
scrollback_pager sh -c 'cat > /tmp/kitty_scrollback && KITTY_SCROLLBACK=1 nvim -c "set clipboard+=unnamedplus" -c "term cat /tmp/kitty_scrollback -"; rm -f /tmp/kitty_scrollback'
map ctrl+space>k show_scrollback

# TODO: send commands from one window to another from nvim?
