# Open directories
protocol file
mime inode/directory
action launch --type=background xdg-open "${FILE_PATH}"

# Open image files
protocol file
mime image/*
action launch --type=background xdg-open $FILE_PATH

# Open video files
protocol file
mime video/*
action launch --type=background xdg-open $FILE_PATH

# Open (remaining mime types) text files without fragments in the editor
protocol file
action launch --type=overlay -- $EDITOR -- $FILE_PATH
