[env]
term = "xterm-256color"

[shell]
program = "wsl"
# Use default wsl version
args = ["-d", "--cd", "~"]

[window]
padding = { x = 8, y = 8 }
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 5

[font]
size = 15
#normal = { family = "MesloLGS NF", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
offset = { x = 0, y = 0 }

[selection]

semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]

style = { shape = "Beam", blinking = "Off" }

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
  { key = "v", mods = "Control", action = "Paste" },
  { key = "n", mods = "Control | Shift", action = "SpawnNewInstance" },
]
