name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download all workflow run Artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: wsl-distro-custom.yml