name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-other-artifact
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          repository: actions/toolkit
          run-id: 1234