name: Sync q files

on:
  workflow_dispatch:
  schedule:
    # Run at 00:00 UTC daily
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOTFILES_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Clone private qoolbox repository
        run: |
          git clone git@github.com:mau-mauricelim/qoolbox.git
      - name: Copy q files
        run: |
          rsync -av qoolbox/q.q qoolbox/lib ./q/
      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add q/
          git diff --quiet && git diff --staged --quiet || git commit -m "Sync q files"
          git push
